### ISSUE TITLE
Deploying Shiny app to Shinyapps.io ,using rdrop2

### ISSUE THREAD

**Issue by rohan19250** [karthik/rdrop2#61] opened 2017-01-10 22:39 UTC
I know the connection to dropbox is working,I have been able to create folders (Single_Cell_RNAseq_data) and move files.
My app is running fine when I run the app locally in R Studio ,the data gets uploaded from the dropbox and can be visualized.

## saved the token locally
 
```
token <- drop_auth()
saveRDS(token, "droptoken.rds")
```

 
##in the global.r Script
```
token <- readRDS("droptoken.rds")
geneExpressionMatrix_yf1 <- drop_read_csv("Single_Cell_RNAseq_data/geneExpressionMatrix_yf1.csv",dtoken=token)

```
But while deploying on shinyapps.io, its throwing me this error.

An error has occurred
Unable to connect to worker after 60.00 seconds; startup took too long.

**Comment by TheBiro** [comment] 2017-02-07 18:51
I don't know if this is what you're looking for, but try reading this:

https://daattali.com/shiny/persistent-data-storage/

**Comment by daattali** [comment] 2017-03-09 06:12
I'm also currently seeing problems with saving the auth token (I wrote the app that @TheBiro pointed to)

**Comment by ericpgreen** [comment] 2018-09-20 17:06
Are folks still having issues? I came across @daattali's excellent post on remote storage for Shiny apps, got everything running locally, then ran into problems in Connect (on a trial now, may move to shinyapps.io). 

When publishing from RStudio I included the `droptoken.rds` file and called the following in the global: 

```
token <- readRDS("droptoken.rds")
drop_acc(dtoken = token)
```
Have I missed a step?
In the logs, I as an admin can see Connect wants me to authenticate in the browser. 

> Waiting for authentication in browser...

**Comment by ClaytonJY** [comment] 2018-09-20 17:35
Well, that looks like a real token! Unfortunately I haven't the slightest clue what's going on here.

I've never had any issues using RDS tokens on ShinyServer instances I install/control, and it's hard to imagine what would be different about Connect.

**Comment by ericpgreen** [comment] 2018-09-20 18:58
I tried on shinyapps.io as well. I just get the "please wait" animation. In the logs I can see: 

```
2018-09-20T18:54:03.639549+00:00 shinyapps[458677]: Waiting for authentication in browser...
2018-09-20T18:54:03.640039+00:00 shinyapps[458677]: Press Esc/Ctrl + C to abort
2018-09-20T18:54:03.625398+00:00 shinyapps[458677]: Adding .httr-oauth to .gitignore
2018-09-20T18:54:03.642615+00:00 shinyapps[458677]: https://www.dropbox.com/oauth2/authorize?client_id=XXXXXXXXXXXX&redirect_uri=http%3A%2F%2Flocalhost%3A1410%2F&response_type=code&state=XXXXXXXXX
2018-09-20T18:54:03.642116+00:00 shinyapps[458677]: Please point your browser to the following url: )
```

Does this give any hints?

**Comment by ClaytonJY** [comment] 2018-09-20 19:20
Unfortunately it doesn't; I'm not sure how you're hitting the auth codepath when using `drop_acc`; if the token is bad, you should get a negative response from Dropbox, but not be sent through the auth flow.

Is it possible there's another call to a `drop_*` function, _after_ `drop_acc`, where you don't pass in the token? That would trigger `rdrop2:::get_dropbox_token`, which would trigger the auth flow you're seeing. This might not replicate locally because of `.httr-oauth` hanging around.

What happens if you explicitly call `drop_auth`, like this?

```r
drop_auth(rdstoken = "droptoken.rds")  # don't read it first
drop_acc()
```

That's the recommended (but not well documented) solution for using `rdrop2` remotely; set the token _once_, then don't worry about the `dtoken` arg everywhere else.

**Comment by ericpgreen** [comment] 2018-09-20 20:31
Yes! I had `drop_upload(file.path(tempdir(), "master.csv"), path = outputDir)`

I misunderstood:

```
# Then pass the token to each drop_ function
drop_acc(dtoken = token)
```

To mean: "by running `drop_acc(dtoken = token)`, you will automatically pass the token to each drop_ function". It worked locally despite my ignorance for the reason you stated.

Right now I am able to load the app remotely, but I need to investigate a bit further to know if it is related to authentication. Thanks for your help troubleshooting! I'll post back.

**Comment by ericpgreen** [comment] 2018-09-20 20:51
I fixed the new problem (in troubleshooting I moved a reference to an `input$` to the `global` chunk) and confirmed everything is working locally again. 

1. I tried running `token <- readRDS("droptoken.rds")` AND `drop_acc(dtoken = token)` AND adding `dtoken = token` to all `drop_` functions: still have the remote error of needing to authenticate via the browser.

2. Running your approach of `drop_auth(rdstoken = "droptoken.rds")` AND `drop_acc()` AND keeping `dtoken = token` in all functions produced the same result.

3. Repeating 2 but dropping `dtoken = token` from the functions produced the same result as well. 

Is there a way to store `.httr-oauth` remotely? @daattali seems to refer to this [here](https://deanattali.com/blog/shiny-persistent-data-storage/#local-vs-remote), but I don't know if that is possible on `.io`:

> The authentication approach I chose was to authenticate manually once and to copy the resulting .httr-oauth file that gets created into the Shiny app’s folder.

@rghertner mentions a different approach [here](https://github.com/karthik/rdrop2/issues/48#issuecomment-207173265):

> Instead of stating `drop_acc(dtoken = token)`, explicitly put in the `dtoken=your_token` as the last parameter in all of your functions.

I know this is a dumb question, but I'm not clear on where to find the value of `your_token`. Is that what I did in 2 and 3 above? Or is there a different token? (I looked at creating an "app" on Dropbox, and it seems that approach gives a token that is a string rather than the file we're saving to .`rds`).

Frustrating! I thought I did all the hard work locally. I'm sure I'm just goofing this up.

**Comment by ClaytonJY** [comment] 2018-09-20 20:54
Great, we're getting somewhere!

To be extra clear for future readers, for a shiny app you should include your token as an RDS, and then either
1. authenticate with that token like `drop_auth(rdstoken = "tokenfile.rds")` in `global.R` or at the top of `server.R`, then call other `drop_*()` functions normally (without using the `dtoken` arg)
1. do *not* call `drop_auth()`, read the token into R from the RDS file, then pass that token object into _every_ `drop_*()` function through the `dtoken` arg

I think the first option is much, much better (and is what I do), but the second should still be viable.

**Comment by ClaytonJY** [comment] 2018-09-20 21:03
Sorry @ericpgreen, posted my comment above before seeing your second one.

I suggest _not_ reading in the token yourself, passing the path to `drop_auth` (this must happen before any other calls, so put it in `global.R`, which it sounds like you might be doing already), and calling all the other functions _without_ `dtoken`.

It sounds like you did that in your trial (3) above. It seems like the token is being transferred, because if the file doesn't exist then `drop_auth` should throw an error like "token file not found". Could you be doing it in the wrong place, so that a different drop function is being called before auth? That's my only guess at the moment, unfortunately.

**Comment by ericpgreen** [comment] 2018-09-20 21:34
Victory! Using option 1:

Only running `drop_auth(rdstoken = "droptoken.rds")` and no `dtoken` arg in the `drop_` functions. I also moved one `drop_` function out of the global chunk (I'm running flexdashboard). It came after the authentication steps, but maybe it was causing a problem.

Works on `.io` and connect (as it should).

Very much appreciated, @ClaytonJY!

**Comment by ClaytonJY** [comment] 2018-09-20 21:42
Awesome! I was really running out of ideas on what could be going wrong, so I'm very glad that worked.

**Closed by ClaytonJY** 2018-09-20 21:42 UTC
Labels: rdrop-0.7

**Comment by danwiththeplan** [comment] 2021-03-18 10:40
Sorry to necro but this helped a lot thanks!

**Comment by zeshan304** [comment] 2021-09-17 14:06
> Victory! Using option 1:
> 
> Only running `drop_auth(rdstoken = "droptoken.rds")` and no `dtoken` arg in the `drop_` functions. I also moved one `drop_` function out of the global chunk (I'm running flexdashboard). It came after the authentication steps, but maybe it was causing a problem.
> 
> Works on `.io` and connect (as it should).
> 
> Very much appreciated, @ClaytonJY!

hi i dont know if after three year you ppl might get this or not but i am facing same problem as that of  
@ericpgreen was facing in 2018. but after you conversation i am still doubt how to handle this issue cany any body elaborate with any chunk code. pardon i dnt have any CS backgroud plus very new on shiny and rdrop

**Comment by zeshan304** [comment] 2021-09-17 14:09
@ericpgreen i have tried alot by putting in .server or  out of server but not finding how to get out of this same problem
the app is totaly active in local computer but not working for shinyapp.io

**Comment by ericpgreen** [comment] 2021-09-17 16:24
@zeshan304 I'm not sure this will help, but I searched my files for `drop_` and grabbed lines that seem relevant. This is not a full working example (and it's shiny in a flexdashboard, not pure shiny).

````
---
title: "Title"
resource_files:
- droptoken.rds
- custom.css
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    css: custom.css
    orientation: columns
    theme: bootstrap
    vertical_layout: fill
---

```{r global, include=FALSE, message=FALSE}
# setup
# -----------------------------------------------------------------------------
  library(flexdashboard)
  library(shiny)
  library(rdrop2)
  library(tidyverse)
  
# authenticate with dropbox for remote storage
# -----------------------------------------------------------------------------
# https://github.com/karthik/rdrop2
# https://github.com/karthik/rdrop2/issues/61#issuecomment-423341288
# run once:
  # drop_auth()
  # token <- drop_auth()
  # saveRDS(token, file = "token.rds")   # updload to server with app
  
  outputDir <- "dash"                    # output directory on Dropox (toplevel)
  drop_auth(rdstoken = "droptoken.rds")  # give token
```

```{r load, include=FALSE, message=FALSE} 
# load files
  main <- reactiveValues(df = drop_read_csv("file.csv", stringsAsFactors = FALSE))
```

```{r something}
# submit data
# -----------------------------------------------------------------------------
  observeEvent(input$submit, {
    
# do some stuff
    
# save to dropbox
  write.csv(main$df, file.path(tempdir(), "main.csv"), row.names = FALSE, 
            quote = TRUE)
    drop_upload(file.path(tempdir(), "main.csv"), path = outputDir)

# do some stuff

})
```
````

**Comment by zeshan304** [comment] 2021-09-22 11:25
Thanks a lot its working now
