### ISSUE TITLE
CSV file not being overwritten.

### ISSUE THREAD

**Issue by usmansuleman** [karthik/rdrop2#55] opened 2016-08-31 04:02 UTC
Thank you for your app.
It works very well.  However, the problem I have is drop_upload a csv file with overwrite=TRUE.  This argument is being ignored or the problem is with DropBox sync.  Some files get over-written, others don't.   But, I added code to check if drop_exists, drop_delete if TRUE, then drop_upload and this works.

**Comment by karthik** [comment] 2017-09-20 04:03
This is currently fixed in the next update to `drop_upload` as this is a supported feature in the v2 api. Please update the package once it's up next week.

**Closed by karthik** 2017-09-20 04:03 UTC
Labels: rdrop-0.7

**Comment by eafpres** [comment] 2018-09-01 18:12
I am having issues with this same behavior.  Here is my code:
      file_path <- file.path(tempdir(), "linear_model.RDS")
      drop_download(path = file.path(db_folder, "linear_model.RDS"), 
                    local_path = file_path,
                    overwrite = TRUE)
      lin_model <- readRDS("linear_model.RDS")

The model is the old version from a previous run, it is not being overwritten.

**Comment by ClaytonJY** [comment] 2018-09-19 04:10
hi @eafpres, the issue is that you're not reading from `file_path`, so the last line in your example is not reading from where you just downloaded to.
